name: Test Workflow

on:
  repository_dispatch:
    types: [test-workflow]


permissions:
  contents: write

jobs:
  CreateJsonString:
    runs-on: ubuntu-latest
    outputs:
      badgeJsonString: ${{ steps.createBadgeJsonString.outputs.badgeJsonString }}

    steps:
      - id: createBadgeJsonString
        run: |
          jsonString="{\"label\": \"${{ github.event.client_payload.label }}\", \"message\": \"${{ github.event.client_payload.message }}\", \"color\": \"${{ github.event.client_payload.color }}\"}"
          echo $jsonString
          echo "badgeJsonString=$jsonString" >> $GITHUB_OUTPUT
          

  PushJsonFile:
    needs: CreateBadgeJsonString
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CreateJsonFile
        id: createJsonFile
        run: |
          badgeFileName="${{ github.event.client_payload.badgeId }}.json"
          echo '${{ needs.CreateBadgeJsonString.outputs.badgeJsonString }}' > "$badgeFileName"
          cat "$badgeFileName"

      - name: CommitFiles
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if [[ "$(git diff-index -p HEAD --)" != "" ]]; then
            git commit -m "Add badge ${{ github.event.client_payload.badgeId }}"
            git push origin HEAD:main
          else
            echo "Badges unchanged. Skipping."
          fi
          
