name: Upload Badge

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Badge label'
        required: true
        type: string
      message:
        description: 'Badge message'
        required: true
        type: string
      color:
        description: 'Badge color'
        required: true
        type: string
      badgeId:
        description: 'Badge id'
        required: true
        type: string


permissions:
  contents: write


jobs:
  CreateBadgeJsonString:
    runs-on: ubuntu-latest
    outputs:
      badgeJsonString: ${{ steps.createBadgeJsonString.outputs.badgeJsonString }}
    steps:
      - name: Create badge json string
        id: createBadgeJsonString
        run: |
          jsonString="{\"label\": \"${{ github.event.inputs.label }}\", \"message\": \"${{ github.event.inputs.message }}\", \"color\": \"${{ github.event.inputs.color }}\"}"
          echo $jsonString
          echo "badgeJsonString=$jsonString" >> $GITHUB_OUTPUT

  PushJsonFile:
    needs: CreateBadgeJsonString
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CreateJsonFile
        id: createJsonFile
        run: |
          badgeFileName="${{ inputs.badgeId }}.json"
          echo '${{ needs.CreateBadgeJsonString.outputs.badgeJsonString }}' > "$badgeFileName"
          cat "$badgeFileName"

      - name: CommitFiles
        run: |
          if [[ "$(git diff-index -p HEAD --)" != "" ]]; then
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add .
            git commit -m "Add badge ${{ inputs.badgeId }}"
            git push origin HEAD:main
          else
            echo "Badges unchanged. Skipping."
          fi
          
          
    



          
